### ISSUE TITLE
Images being rotated by the plugin

### ISSUE THREAD

**Issue by AlexR1** [vvvmax/unitegallery#122]
Hello
First of all, it is very nice plugin that is very easy to use thanks to your descriptive site.

Second, I ran into a weird issue.
I noticed that the plugin rotates some images (src and data-image) without me able to stop it.
The images are ones with width smaller than height (i.e. standing rectangle).
Happens both for different tiles types. For example: nested or justified.

Is there a way to fix this?

thanks!
Alex

**Comment by AlexR1** [comment]
Seems like the issue caused by SharePoint..

**Comment by vvvmax** [comment]
oh, cool. glad that you found it out.
