### ISSUE TITLE
Load Images from json

### ISSUE THREAD

**Issue by mhmtwork** [vvvmax/unitegallery#15]
load images (big image and thumbs) from urls or  json. Count of images are changeable for each page or request.
    <div id="gallery" style="display:none;">
            <img alt="Image 1 Title" src="thumbs/image1.jpg"
                data-image="images/image1.jpg"
                data-description="Image 1 Description">
            <img alt="Image 2 Title" src="thumbs/image2.jpg"
                data-image="images/image02.jpg"
                data-description="Image 2 Description">
        </div>

Above part will not be at .html
Can I reate this part at javascript file with for loop  from json or array

**Comment by vvvmax** [comment]
answered in private email.

**Comment by mhmtwork** [comment]
thanks for your answer.
