### ISSUE TITLE
Consider adding tags for the repo.

### ISSUE THREAD

**Issue by Piicksarn** [vvvmax/unitegallery#18]
Hi~
Adding tags for repo could specify points in history and mark release points.
It's helpful for user to know the version and status of repository, and would enable wider distribution of the library, for example on [CDNJS](https://github.com/cdnjs/cdnjs)
Would you please consider on using tags?

Thanks for your great work!!
Piicksarn

**Comment by vvvmax** [comment]
Hi. I don't understand what tags are. And I don't see it in git hub. Could
you please explain?

**Comment by Piicksarn** [comment]
@vvvmax 
the link below show more detail about tagging.
https://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by vvvmax** [comment]
Hi. It would be too complicated for me. I like it simple. do update and
upload it to github.

**Comment by Piicksarn** [comment]
@vvvmax, it's fine :)))
Thank you for response!
