### ISSUE TITLE
add tags for each version

### ISSUE THREAD

**Issue by maruilian11** [vvvmax/unitegallery#20]
would you please consider adding tags for each version so that we can add your lib on https://cdnjs.com/ with git autoupdate.
thank you very much!
https://github.com/cdnjs/cdnjs/issues/5373

**Comment by vvvmax** [comment]
Hi. do you know how to do it? I'm new in github. If you show me how you do
it, I'll do it.

if so, Please give me your email, I'll email you from my private one and
you'll guide me.

**Comment by maruilian11** [comment]
@vvvmax hope this will help you!
https://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by Naki** [comment]
Simply go to [releases](https://github.com/vvvmax/unitegallery/releases) tab which can be found on main page of repository.
Open new release form by using button: "*Create a new release*".

Enter tag version, for example: v1.6.6
Use select input on right, and switch to "*Recent commits*" then select v1.6.6 commit.

You can fill release title and description (like "*Unite Gallery v1.6.6*" in title and changelog in descrption) but it is not required.

Finish by submitting "*Publish release*".

It is really fast and very helpful to be up-to-date with Yours library :).

Regards.

**Comment by vvvmax** [comment]
ok, thanks a lot! Did it :)
