### ISSUE TITLE
Uncaught SecurityError when i add social plugin G+, Facebook

### ISSUE THREAD

**Issue by nerarosa** [vvvmax/unitegallery#21]
I add +1 button and FB like share to page , Console display error:

<code>Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://mydomain.com" from accessing a frame with origin "https://apis.google.com".  The frame requesting access has a protocol of "http", the frame being accessed has a protocol of "https". Protocols must match.

Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://mydomain.com" from accessing a frame with origin "http://static.ak.facebook.com". The frame being accessed set "document.domain" to "facebook.com", but the frame requesting access did not. Both must set "document.domain" to the same value to allow access.

Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://showsexygirl.blogspot.com" from accessing a frame with origin "https://s-static.ak.facebook.com".  The frame requesting access has a protocol of "http", the frame being accessed has a protocol of "https". Protocols must match.</code>

How to fix, pleases???

**Comment by vvvmax** [comment]
Hi. The gallery dont have support for social sharing buttons so i cant
support this issue, sorry. Will add it in the future.

**Comment by nerarosa** [comment]
Thanks!!!
