### ISSUE TITLE
Can't fire unitegallery again

### ISSUE THREAD

**Issue by DevCilla** [vvvmax/unitegallery#22]
Hi, I cannot call the  $(#'selector').unitegallery() again after closing the gallery,
i.e. only the first call success, the other calls of the same element will get errors.
I get the 'Uncaught Error: The item should not be image type'.

How can I fix this? Thanks for your help.

**Comment by vvvmax** [comment]
Sure you can't do it. what for you need to call it twice? :)

**Comment by pokemonTrainee** [comment]
Thanks for your reply.
because I wish the gallery would be fired by other event, e.g. by clicking a button, instead of clicking the images in the gallery.

Below is my original code:
<button onclick="openGallery()">Open Gallery</button>

function openGallery(){
 var gallery = $('#gallery').unitegallery();
gallery.enterFullscreen();
}

**Comment by vvvmax** [comment]
so do it only once. also, you can hide the gallery like making some div
opacity:0 and then just go fullscreen on button click. that way it won't
work, because the gallery needs some time to initiate.

**Comment by pokemonTrainee** [comment]
Thanks for your advice, I solved the problem

    <button onclick="openGallery()">Open Gallery</button>

```javascript
//global declare
var gallery;
function setGallery(){
   gallery = $('#gallery').unitegallery();
   $('#gallery').css({'opacity': '0.0', 'max-height':'0', 'max-width':'0'});
} 

function openGallery(){
   gallery.enterFullscreen();
}
```

**Comment by vvvmax** [comment]
Ok. Cool.

**Comment by KOPOJI** [comment]
Well, it's cool. Why I can't call it twice!?
It's fail library

**Comment by vvvmax** [comment]
HI. what you can't call twice? I don't understand.

**Comment by KOPOJI** [comment]
> Hi, I cannot call the $(#'selector').unitegallery() again after closing the gallery,
> i.e. only the first call success, the other calls of the same element will get errors.
> I get the 'Uncaught Error: The item should not be image type'.
> 
> How can I fix this? Thanks for your help.
I get the 'Uncaught Error: The item should not be image type' too.

**Comment by vvvmax** [comment]
HI. I don't have this option to public yet (it's undocumented), but it's a
part of API.

You can use api.reloadGallery(opt) - the same gallery with another options.


You can see how I use it here:

http://unitegallery.net/index.php?page=tiles-columns-variuos

here is the code:

http://unitegallery.net/js/custom.js


to use the same gallery with another items I don't have public option yet
even in API, sorry. I'll add it in the future.

**Comment by KOPOJI** [comment]
$('#foo').unitegallery();
$('#bar').unitegallery();
or
$('#foo, #bar').unitegallery();
==
Uncaught Error: The item should not be image type. 
This is often needed. Good luck

**Comment by dhavalshah01** [comment]
I was able to resolve this issue. Generally when we try to re-bind the existing unitegallery, we face this error. If you want to re-bind the gallery with the new option use the method reloadGallery.

if(!ImgGallery){
        console.log("Frist time");
        ImgGallery =  $("#newsGallery").unitegallery({
			gallery_theme: "slider",
			slider_enable_arrows: true
       	});
      }else{
        console.log("every subsequent time");
        ImgGallery.reloadGallery({
			gallery_theme: "slider",
			slider_enable_arrows: false
        
      });
}
