### ISSUE TITLE
checkMinJqueryVersion function wrong validation

### ISSUE THREAD

**Issue by comproperty247** [vvvmax/unitegallery#26]
Message on page 
"Unite Gallery Error: The gallery can run from jquery 1.8 You have jQuery 2.1.0 Please update your jQuery library."

I have  jquery loaded with version 2.1.0 and the minimum version required is 1.8.0,
In function checkMinJqueryVersion outputs a wrong validation!!
After spliting the versions by "." it does like this
1º step - 2>1 => true
2º step - 1>8 => false => outputs "!1" . which is wrong!!! because in fist step 2 is bigger than 1, in other words 2.1 is bigger than 1.8

**Comment by vvvmax** [comment]
Ok. Thanks. Ill fix it tomorrow morning right away! Today just dont have
the ability. Thanks.

**Comment by comproperty247** [comment]
The lines code are this ones at unitegallery.js:

this.checkMinJqueryVersion = function(version){

	  var $vrs = jQuery.fn.jquery.split('.'),
      min  = version.split('.');
	  
	  for (var i=0, len=$vrs.length; i<len; i++) {			  
	    if (min[i] && parseInt($vrs[i]) < parseInt(min[i])) {
	      return false;
	    }
	  }
	  
	  return true;
	}

I did some quick tests on my console browser Chrome and those lines of javascript works with my "internal" jquery version  jQuery 2.1.0
At console:
 jQuery.fn.jquery > "1.8.0"  => True
jQuery.fn.jquery < "1.8.0"   => False

jQuery.fn.jquery > "2.1.0"  => False
jQuery.fn.jquery < "2.1.0" => False
jQuery.fn.jquery == "2.1.0" => true
jQuery.fn.jquery == "2.1" =>FALSE

Excluding the last result because even is the "same" for us, the machine interprets it differently. 
And you need just to check is if less than a value, perhaps you can use the function like this 

this.checkMinJqueryVersion = function(version){
	  return (jQuery.fn.jquery <  version);
}

I hope this help you ;-)

Regards

**Comment by vvvmax** [comment]
Hi, I just fixed the issue :) Uploaded the new version. Please update yours
and check how I did it if you want.
Tested 100 times with variaty of versions.
