### ISSUE TITLE
Strong dependency on DOM IDs

### ISSUE THREAD

**Issue by TheSisb** [vvvmax/unitegallery#28]
Hi,

In my application we cannot use IDs because of potential content duplication and IDs clashing.  I modified the source to not depend on IDs so tightly, but just pointing out that the strong dependence isn't really beneficial.

Things like "#" + element are also an extra step to compute the concatenated string.  Best if one parent element is found and saved as an object, rather than a substring.

Great library otherwise!

**Comment by vvvmax** [comment]
Hi. Could you send me the source please that you modified to this email:
web.power.net@gmail.com ill check what i could take from it. Thans.

**Comment by TheSisb** [comment]
I actually had to switch back to IDs unfortunately.  I hadn't realized that unitegallery depended on mediaelement.js - which also requires IDs.

**Comment by vvvmax** [comment]
yes, it depends on id's. Sorry, but this is the situation. I can't write a
good player by myself. easier to use a ready one.
