### ISSUE TITLE
One gallery shown when multiple instances initiated

### ISSUE THREAD

**Issue by ayoupov** [vvvmax/unitegallery#29]
Hi, I have pages that need multiple galleries to be shown.

I initiate it this way:
```javascript
function galleries() {
    $(".content-gallery").each(function (a, gallery) {
        var gallOpts = DEFAULT_GALL_OPTS;
        var $gall = $(gallery);
  // setting options
        $gall.unitegallery(gallOpts);
    });
```
html markup:
```html
<div id="gallery_2" class="content-gallery" style="width: 740px; margin-left: -140px; height: 400px;">
  <img src="/1.png" data-image="/1.png" alt="Title1" class="content-image" style="width: 740px;">
  <img src="/2.jpg" data-image="/2.jpg" alt="ttt" class="content-image" style="width: 740px;">
</div>
<div id="gallery_1" class="content-gallery full-width">
  <img src="/1.png" data-image="/1.png" alt="Title1" class="content-image">
  <img src="/3.png" data-image="/3.png" alt="Caption!" class="content-image" >
  <img src="/4.jpg" data-image="/4.jpg" alt="Pec" class="content-image">
</div>
```

Alas, it shows only the first gallery. Any ideas?

**Comment by vvvmax** [comment]
HI. each gallery should have "ID". The gallery init is ID specific.


On Thu, Sep 10, 2015 at 9:26 PM, Alexander Ayoupov <notifications@github.com

**Comment by ayoupov** [comment]
Am I missing something, as markup I provided has two divs with ids: _gallery_2_ and _gallery_1_.

**Comment by vvvmax** [comment]
Can you please give me link to this file online?

**Comment by ayoupov** [comment]
Yes, sure: 
http://panaggelica.org/asdgallery/asdgallery.html
My project uses jquery 1.9, but changing to 1.11 seems to do no change.

**Comment by vvvmax** [comment]
ok. cool. I'll check it tomorrow morning,

On Fri, Sep 11, 2015 at 5:21 PM, Alexander Ayoupov <notifications@github.com

**Comment by vvvmax** [comment]
Please check the height on second case. You must set gallery height when
width is 100%

**Comment by ayoupov** [comment]
Thanks. It's a bit weird, but that helped

**Comment by MikMuller** [comment]
Still only seeing one gallery. Is there no way to have two appear on one page? Like, a slider and a tile?

**Comment by vvvmax** [comment]
HI, please give different ID to each gallery.

**Comment by jeffreyvr** [comment]
While this ticket is closed I'd like to share my solution to this issue;

```javascript 
if ( typeof UniteGalleryMain == 'function' ) {
    $('div[id^="tiled-gallery"]').each(function(){
      $(this).unitegallery({
        tiles_type: "justified",
        lightbox_type: "compact",
        theme_enable_preloader: "false"
      });
    });
  }
```

So this loops through all occurrences of tiled-gallery's. I have set the id's to be like tiled-gallery-1, tiled-gallery-2 etc..
