### ISSUE TITLE
Can not display the gallery on init

### ISSUE THREAD

**Issue by maverick42** [vvvmax/unitegallery#3]
Hi,

Wonderfull library !

In my case, I would not display the gallery #div on init (page) but only when the I switches to fullscreen mode (I want to see the gallery ONLY in fullscreen mode) . 
Actually the gallery #div is displayed on the init ....

g_uniteGallery = jQuery("#hbt-gallery").unitegallery({
                gallery_theme: "grid",
                theme_panel_position: "right",
                slider_scale_mode: "fit"
            });

            g_uniteGallery.on("enter_fullscreen", function () {
                $("#hbt-gallery").show();
            });

            g_uniteGallery.on("exit_fullscreen", function () {
                $("#hbt-gallery").hide();
            });

Regards 
Frederik

**Comment by vvvmax** [comment]
Hi, Please try to do it with this version of the gallery (1.3). Maybe it
will be success.
Generally the gallery won't load if the container div display:none. But I
done some update, maybe it will be done.
Please tell me if it's working or not, I'll update the gallery on github if
it's working.

**Comment by maverick42** [comment]
"Please try to do it with this version of the gallery (1.3)."
Where I can find this version ?? ! :)
Thxs
Frédérik

**Comment by vvvmax** [comment]
I have sent you it attached. (file attachment).

**Comment by maverick42** [comment]
I really sorry but I can't find it ....
I'm not at ease in github manipulations.. 
Frédérik

**Comment by maverick42** [comment]
Hi,
any news ... ? I unfortunately find any link file ....
regards 
Frédérik

**Comment by vvvmax** [comment]
HI, shared it in dropbox. Please check it here:

https://www.dropbox.com/s/7brmrab0dko0fk1/unitegallery.zip?dl=0

**Comment by maverick42** [comment]
Hi,
Thanks for your help.
Unfortunately it does not work (as I would : ))
After init I always have to hide the "div" window. Because it appears
I use handlebars but I think this should not be related

My original div
<div id="hbt-gallery" style="margin:0px auto;display:none;">
</div>

and my "action" zoom button :
var actionZoomPhoto = function (imgPosition) {
            if (g_uniteGallery === null) {
                var xTemplate = Handlebars.compile($("#x-hbt-gallery").html());
                $('#hbt-gallery').html(xTemplate(g_carousel));

                g_uniteGallery = jQuery("#hbt-gallery").unitegallery({
                    gallery_theme: "grid",
                    theme_panel_position: "right",
                    slider_scale_mode: "fit"
                });
                $("#hbt-gallery").hide(); // .....

                g_uniteGallery.on("enter_fullscreen", function () {
                    $("#hbt-gallery").show();
                });

                g_uniteGallery.on("exit_fullscreen", function () {
                    $("#hbt-gallery").hide();
                });
            }

            // on lance la super galerie :)
            g_uniteGallery.selectItem(imgPosition);
            g_uniteGallery.enterFullscreen();
        };

I prefer init the gallery on zoom button event because I not want to load any "large" images
on the main load page because it is not obligatory to zoom photos ...

Regards
Frédérik

**Comment by maverick42** [comment]
Note that anyway it  works ....  it would just make it even better :)

**Comment by vvvmax** [comment]
Hi. I don't understand completely what you trying to do. If you give me url
to your website I'll take a look and maybe understand if clearly.

**Comment by maverick42** [comment]
Hi,
It's a vpn web site ; it is not possible. So I made screen shots to help you

http://4yoo.fr/img/gallery_1.jpg
As you see I have a a "first" gallery (with superbox.js)

When I click on a picture  http://4yoo.fr/img/gallery_2.jpg
we open a window with large picture and the option to open your gallery (in fullscreen mode) by clicking the "zoom" button

regards
Frederik

**Comment by vvvmax** [comment]
HI. I think what you need is not fullscreen, but open the gallery on some
lightbox. You can do it with fancybox I think, to open some saparate page
where the gallery is located.

Anyway, I think that you can put the gallery on some fixed size div, make
it some size, not metter what, and make it opacity:0, not display: none.
This way the gallery will oppear, but will remain hidden. Maybe it will
help you.

**Comment by maverick42** [comment]
I see what you think... I was using other libraries before like fancybox (exactly this http://osvaldas.info/image-lightbox-responsive-touch-friendly)
But yours is "perfect". In fullscreen mode I can (still) navigate all my photos with annotation and especially make a huge zoom on each! This is exactly what my users want ..!
So I'll leave my javascript code as now because it works well anyway!

Thank's for your help
Fréderik

**Comment by vvvmax** [comment]
Ok. Cool. Good luck!
