### ISSUE TITLE
Plugin stops propagation of all left/right arrow key presses events

### ISSUE THREAD

**Issue by erinsasha** [vvvmax/unitegallery#40]
Hello Max!

I’ve noticed that Unitgallery catches left/right arrow key pressing events and stops their propagation. So when focus is in a textarea, the user can switch between rows by pressing up/down arrow key, but he/she can’t move cursor to left or right.
Can you add some option, which will tell the plugin: catch left/right arrow key pressing events only, if Unitgallery element has :hover or :focus state or some sort of that?

**Comment by vvvmax** [comment]
hi, dont understand what you mean. can you please explain another time in
different way? focus what?

**Comment by erinsasha** [comment]
Sorry it seems in my previous message the word “textarea” was hidden because it was wrapped as a tag. Also :hover or :focus in the message are CSS or jQuery selectors http://www.w3schools.com/cssref/css_selectors.asp.
I mean that the plugin must catch keyboard events only when a user works with a gallery. For example, if you add textarea element into your …/source/index.html, it will not allow you left/right movement of the cursor.

**Comment by vvvmax** [comment]
HI. The gallery can't catch events from inside textarea, sorry. No plugin
can.

**Comment by vvvmax** [comment]
Hi, Now I'm understand what you mean. Fixed the bug in current release. Please check.

**Comment by erinsasha** [comment]
It works. Thank you!

**Comment by vvvmax** [comment]
Cool! Good luck!
