### ISSUE TITLE
Portrait images are not displayed correctly

### ISSUE THREAD

**Issue by cristianrosu** [vvvmax/unitegallery#5]
Portrait images should be displayed in 'contain' mode. Right now, they are zoomed in until they fill in the entire slider width. Any idea on how can I fix this?

**Comment by vvvmax** [comment]
Hi. you have 3 scale modes. Please play with them.

slider_scale_mode: "fill", //fit: scale down and up the image to always fit
the slider  //down: scale down only, smaller images will be shown, don't
enlarge images (scale up)
