### ISSUE TITLE
Resizing of thumbs in tilesGrid

### ISSUE THREAD

**Issue by Peter74** [vvvmax/unitegallery#56]
Hi,
I try to search in documentation, but I did not find it.
I have set gallery_width and height to 100%, which is OK, but thumbnails are scaled down to 180 x 150px.
How I can change width and height of tilesgrid thumbnails (my source images have 250 x 208px) ?

**Comment by vvvmax** [comment]
HI. please show me the gallery so I could look. I can't understand what you
want to do

**Comment by Peter74** [comment]
Hi,

I send you e-mail with link.

**Comment by Peter74** [comment]
Hi, please did you receive e-mail from me?

**Comment by Peter74** [comment]
..now i see :) you include options in each example - that is really useful and solve this issue for me.
Really thanks!
