### ISSUE TITLE
lightbox wide: next button on last image goes to first image > true/false

### ISSUE THREAD

**Issue by dddesign** [vvvmax/unitegallery#61]
in the default theme there is an option gallery_carousel:true/false which controls if there is a next button on last image goes to first image (carousel).

it would be very nice, if a similiar option would exist for lightbox wide!

thanks j

**Comment by dddesign** [comment]
any news on this? it would be very nice to get this feature! j

**Comment by vvvmax** [comment]
oh, I didn't see the post you made last time.
I'll check the issue and come back to you within 3-4 days.

**Comment by dddesign** [comment]
I found it: this option already exits:
gallery_carousel:true,	//true,false - next button on last image goes to first image.
