### ISSUE TITLE
Which files need to be hosted

### ISSUE THREAD

**Issue by pvnr0082t** [vvvmax/unitegallery#63]
Hi @vvvmax 
We are [cdnjs](https://github.com/cdnjs/cdnjs) team, we want to host your project on cdnjs.
But I don't know which files in this repo need to be added, could you help up find out the main files?
Thank you.

https://github.com/cdnjs/cdnjs/issues/7032

**Comment by vvvmax** [comment]
Hi.
Please you welcome :)
there are the plugin files:

https://github.com/vvvmax/unitegallery/tree/master/package/unitegallery

in the package/unitegallery folder.
This would be enought for show the gallery on any site.

if you missing something more that I can do like adding some tag or
something, please let me know.
