### ISSUE TITLE
Add git tags and check the version

### ISSUE THREAD

**Issue by pvnr0082t** [vvvmax/unitegallery#64]
Hi @vvvmax ,
Is that the latest released version is v1.7.14? If yes, could you please add the git tag for the latest version? Thank you.

https://github.com/cdnjs/cdnjs/issues/7032

**Comment by vvvmax** [comment]
HI. sorry. There is the tag (last version).

https://github.com/vvvmax/unitegallery/releases/tag/1.7.14

I'll try to update the tags on every last release.

**Comment by pvnr0082t** [comment]
Thank you for your help : )
