### ISSUE TITLE
About released files

### ISSUE THREAD

**Issue by pvnr0082t** [vvvmax/unitegallery#65]
Hi @vvvmax ,
Hi, I'm going to add this lib to [cdnjs](https://github.com/cdnjs/cdnjs).
Is it possible to add a ```dist``` folder for released files which in the package/unitegallery folder? Thank you.

https://github.com/cdnjs/cdnjs/issues/7032
https://github.com/cdnjs/cdnjs/pull/7621

**Comment by vvvmax** [comment]
what you mean dist folder? where? empty folder?

**Comment by pvnr0082t** [comment]
The ```dist``` folder is for the auto-update in ```cdnjs``` to easily get the main files.
There are some example:
https://github.com/nnattawat/flip
https://github.com/ichord/Caret.js
https://github.com/sayanee/angularjs-pdf

So, maybe you can create a new folder named ```dist``` for this repo and put folders which in ```package/unitegallery``` into ```dist``` folder.

If there is anything not clear, feel free to ask. :) Thank you.

**Comment by vvvmax** [comment]
HI. added dist folder. Please check if all ok.

https://github.com/vvvmax/unitegallery/tree/master/dist

**Comment by pvnr0082t** [comment]
Thanks for your help.
