### ISSUE TITLE
Tiles Grid Theme next panel thumb position error

### ISSUE THREAD

**Issue by geek01** [vvvmax/unitegallery#76]
if(rowsCounter >= g_options.grid_num_rows){
					
					//change to a new pane					
					rowsCounter = 0;
					baseX = posx;
					posy = baseY;
					paneMaxY = 0;//<=====reset paneMaxY
					
					//change grid width to max width
					if(g_temp.numPanes == 1){
						g_temp.gridWidth = maxx+g_options.grid_padding;
						g_objGrid.width(g_temp.gridWidth);
					}
					
					g_temp.numPanes++;
					g_temp.arrPanes.push(baseX-g_options.grid_padding);
					
				}else{			//start new line in existing pane
					posx = baseX;
					posy = paneMaxY + g_options.grid_space_between_rows;
				}

**Comment by vvvmax** [comment]
HI, it's the max y in each pane. Please tell me where is the problem.

btw, I think I have fixed the issue in the latest version, remember that
was something like this. Please show me on your website where is the bug
you describe, how you see it?

**Comment by geek01** [comment]
My English is pretty basic, Sorry about that.

fix the problem=>
unitegallery.js  about at  line 7511
add >>>>>> paneMaxY = 0;

![2016-05-23t11-51-11 740z](https://cloud.githubusercontent.com/assets/5386866/15470107/f3a30d46-2120-11e6-98d6-8205c2be28c5.png)

**Comment by vvvmax** [comment]
Fixed the issue. Thanks. missed the issue with some of my last updates.
