### ISSUE TITLE
Bower.json

### ISSUE THREAD

**Issue by salarmehr** [vvvmax/unitegallery#79]
may you please add this excellent package to bower?
Also, it would better if you exclude demos and third party js files (jquery) form the bower package.
thanks.

**Comment by vvvmax** [comment]
HI. I"m sorry, I don't know what's bower. Could you please explain to me
what it is and how I need to do it (and why ) ?

**Comment by salarmehr** [comment]
Really? It's hard to believe you don't know bower. 
Please read this: https://css-tricks.com/whats-great-bower/

**Comment by vvvmax** [comment]
Oh, i get it. Its sort of install helper for linux. However, i am not quite
familiar with linux and nit quite understand what i have to change in the
repository. Could you please show me the package i should make? Would be
great if you take my package and add bower related files if its not too
hard for you.  You can write me to vvvmax@gmail.com and send me the file.
Thanks.

**Comment by salarmehr** [comment]
Bower is not related to linux. just install that. Just install node.js and run `npm install -g bower
` on command line. After that read this: http://bower.io/docs/creating-packages/ 
It's far easier that what you imagine.

**Comment by vvvmax** [comment]
Hi, I'll check the issue and come back with some answer. Right now I don't
understand much :(

**Comment by vvvmax** [comment]
Added bower.json. Please check that all ok.

**Comment by salarmehr** [comment]
Thanks. It seems well.
