### ISSUE TITLE
Fullscreen for Tile-Gallery and Carousel possible?

### ISSUE THREAD

**Issue by skerbis** [vvvmax/unitegallery#84]
ist or pissible? I can't find any options for that.

**Comment by vvvmax** [comment]
Hi. Its not posible with tiles type galleries. Sorry. They have lightbox.

**Comment by skerbis** [comment]
ok.

**Comment by skerbis** [comment]
is it possible to replace the lightbox by the behavior the other gallery uses?

**Comment by skerbis** [comment]
or can i replace the lightbox?

**Comment by vvvmax** [comment]
No, sorry. I have only built in lightbox.

**Comment by skerbis** [comment]
ok. Can i mix Images with and without links?

**Comment by vvvmax** [comment]
Yes. You just leave the link empty.

**Comment by skerbis** [comment]
ah cool thx
