### ISSUE TITLE
Video gallery won't load videos displaying spinner forever

### ISSUE THREAD

**Issue by coilt** [vvvmax/unitegallery#85]
Hey! Great gallery, the best I've seen after a real thorough research!

Maybe I'm missing something really obvious here, but I can't seem to load any video in any of the video pages inside freshly downloaded Package. I'm not using any CMS or anything and I'm carefully following instructions regarding js and css links in the <head>, but still no luck.

What am I missing?

**Comment by coilt** [comment]
Oh I'm so sorry for being this stupid. Solved it, it doesn't work on localhost, only on the server.

**Comment by vvvmax** [comment]
Cool! Good luck!

**Comment by jeysinghanbu** [comment]
Still It is not working. Any other way to achieve this?

Thank you.
