### ISSUE TITLE
can i adjust the columns of the justified tiles?

### ISSUE THREAD

**Issue by skerbis** [vvvmax/unitegallery#86]
or is there a solution to get bigger images? 

sorry i found the solution: row height.

**Comment by vvvmax** [comment]
HI, please be more specific. You have some options that relate to the
justified tiles like average tile height etc.
What options exactly do you need?

**Comment by skerbis** [comment]
sorry for my bad english. I've edited my comment. The solution was row height.

**Comment by vvvmax** [comment]
ok, cool! Good luck!
