### ISSUE TITLE
Support for lightbox in default/compact/grid theme

### ISSUE THREAD

**Issue by wodCZ** [vvvmax/unitegallery#9]
Hi,
I'm missing support for lightbox in default/compact/grid themes. 

Thanks to user tracking on our website we have found that users don't know how to close fullscreen gallery (they open gallery, click on black background (=nothing happen) and then leave).
Compact lightbox would be even better.

Any workaround would be great.

**Comment by vvvmax** [comment]
Hi. Its not posible right now, sorry. I should create 2 sliders and link
them to 1 gallery and the gallery object supports only one slider object.
Ill think about that on my later updates.

**Comment by wodCZ** [comment]
Thank you for your fast response.
I switched to tiles grid theme for now.

**Comment by vvvmax** [comment]
Ok. Sorry and good luck. Ill try to think how to accomplish what you said.

**Comment by scooterlord** [comment]
...First of all great job on the plugin!

+1 on this. Would love to have a compact theme with lightbox support! Are you still doing this??

**Comment by vvvmax** [comment]
HI, it's in plans though not first priority. some day will be released :)
meanwhile there is only full screen support.

**Comment by lpredova** [comment]
Are there any news regarding this issue? @vvvmax

**Comment by vvvmax** [comment]
HI, no, sorry. I haven't done this. I am now all in another project, the
gallery runs slow, sorry.
