### ISSUE TITLE
tiles grid bug

### ISSUE THREAD

**Issue by lucaey** [vvvmax/unitegallery#97]
I'm using your gallery plugin and I'm liking it a lot. But when I resize the browser window to minimum the tiles grid changes its paddings to default (20px between rows and columns). Please help me. I can't find the mistake.

**Comment by vvvmax** [comment]
HI. I"m on a vacation right now, and it's hard for me to answer you right.
You have a setting where you change the padding, I have added mobile type
setting as well, just don't documented. Please add "_mobile" as additional
setting example: "grid_padding_mobile:10"
hope that I"m right :)

**Comment by lucaey** [comment]
Thank you for your quick answer. I changed the js code and now it's working perfectly.
